spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      //ddl-auto: update
    
    database: h2
    show-sql: true
    open-in-view: true
    
  datasource:
    name: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testDB
    username: sa